// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc48gnPcZCLNqsUZejbpjBi-aI65hkaLg',
    appId: '1:854447412659:android:0390c36472c2dc504da7c6',
    messagingSenderId: '854447412659',
    projectId: 'flutter-game-2316b',
    storageBucket: 'flutter-game-2316b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoHbXd8FBWDsQpVvAnxUJj6UV01juEXQk',
    appId: '1:854447412659:ios:b812f514a3106bcb4da7c6',
    messagingSenderId: '854447412659',
    projectId: 'flutter-game-2316b',
    storageBucket: 'flutter-game-2316b.appspot.com',
    androidClientId: '854447412659-9iph6q2ib1tipvag7vnfhgtn7igmk0rr.apps.googleusercontent.com',
    iosClientId: '854447412659-shdhf2q5kcvffou2667n9t54g45lt1v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
